services:
  postgres:
    image: postgres:18-alpine3.23
    restart: on-failure
    environment:
      POSTGRES_USER: "smith"
      POSTGRES_PASSWORD: "VlzByjlaU1fx1Ren"
    ports:
      - "5432:5432"
    volumes:
      - smith_postgres_data:/var/lib/postgresql/data

volumes:
  smith_postgres_data: