services:
  postgres:
    image: postgres:18-alpine3.23
    restart: on-failure
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - smith_postgres_data:/var/lib/postgresql/data

volumes:
  smith_postgres_data: