services:
  app:
    build:
      context: .
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
      ENVIRONMENT: ${ENVIRONMENT}
      SERVER_HOST: ${SERVER_HOST}
      VITE_BASE_URL: ${VITE_BASE_URL}
    depends_on:
      postgres:
        condition: service_started
    networks:
      - <app-name>-network
  postgres:
    image: postgres:18-alpine3.23
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - <app-name>_postgres_data:/var/lib/postgresql/data
    networks:
      - <app-name>-network

volumes:
  <app-name>_postgres_data:
networks:
  <app-name>-network:
